# -*- coding: utf-8 -*-
"""Binarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0Yt5IVfp4TU6sfqJFDFRvA-UAahY7JE
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

df = pd.read_csv('Titanic-Dataset.csv')

df

df = pd.read_csv('Titanic-Dataset.csv',usecols=['Age','Fare','SibSp','Parch','Survived'])

df

df.dropna(inplace=True)

df['Family'] = df['SibSp'] + df['Parch']

df.drop(columns=['SibSp','Parch'],inplace=True)

df.head()

X = df.drop(columns=['Survived'])
y = df['Survived']

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import Binarizer

trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['Family'])
],remainder='passthrough')

X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

pd.DataFrame(X_train_trf,columns=['Family','Age','Fare'])

clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

