# -*- coding: utf-8 -*-
"""Binning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fZ8NhbnCHO4T5w1cFtk9Rx6LPHtkeTx
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

df = pd.read_csv('Titanic-Dataset.csv',usecols=['Age','Fare','Survived'])

df.dropna(inplace = True)
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

# NaNs are now dropped before the train/test split in the previous cell

kbin_age = KBinsDiscretizer(n_bins=10,encode = 'ordinal',strategy = 'quantile')
kbin_fare = KBinsDiscretizer(n_bins=10,encode = 'ordinal',strategy = 'quantile')

trf = ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])
])

X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

trf.named_transformers_['second'].bin_edges_

op = pd.DataFrame({
    'Age':X_train['Age'],
    'Age_trf':X_train_trf[:,0],
    'Fare':X_train['Fare'],
    'Fare_trf':X_train_trf[:,1],
})

op.sample(10)

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

def discretize(bins,strategy):
    kbin_age = KBinsDiscretizer(n_bins=bins,encode = 'ordinal',strategy = strategy)
    kbin_fare = KBinsDiscretizer(n_bins=bins,encode = 'ordinal',strategy = strategy)

    Lrf = ColumnTransformer([
        ('first',kbin_age,[0]),
        ('second',kbin_fare,[1])
    ])

    X_trf = trf.fit_transform(X_train)
    print(np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y_train,cv=10,scoring='accuracy')))

    plt.figure(figsize=(14,4))
    plt.subplot(1,2,1)
    plt.hist(X_train['Age'])
    plt.title('Before Discretization (Age)')
    plt.subplot(1,2,2)
    plt.hist(X_trf[:,0])
    plt.title('After Discretization (Age)')
    plt.show()

    plt.figure(figsize=(14,4))
    plt.subplot(1,2,1)
    plt.hist(X_train['Fare'])
    plt.title('Before Discretization (Fare)')
    plt.subplot(1,2,2)
    plt.hist(X_trf[:,1])
    plt.title('After Discretization (Fare)')
    plt.show()

discretize(10,'quantile')

