# -*- coding: utf-8 -*-
"""CCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19R4lszoJX0XgbA4XNRdtrzt8Laxm91cR
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Titanic-Dataset.csv')

cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0]

cols

len(df[cols].dropna())/len(df)

new_df = df[cols].dropna()
df.shape, new_df.shape

new_df['Embarked'].value_counts().plot(kind='bar')
plt.title('Distribution of Embarked')
plt.xlabel('Embarked')
plt.ylabel('Count')
df['Embarked'].value_counts().plot(kind='bar')
plt.title('Distribution of Embarked')
plt.xlabel('Embarked')
plt.ylabel('Count')
plt.show()

