# -*- coding: utf-8 -*-
"""Missing_Indicator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFpcZ-8zpda399D_VwwbUzSu-msku5DM
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

df = pd.read_csv('train (2).csv',usecols=['Age','Fare','Survived'])

df.head()

X = df.drop(columns=['Survived'])
y = df['Survived']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

si = SimpleImputer(add_indicator=True)

X_train = si.fit_transform(X_train)

X_test = si.transform(X_test)

from sklearn.linear_model import LogisticRegression

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

