# -*- coding: utf-8 -*-
"""Multivarient and Bivarient.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EekV71iddcFH87gC3uXCjyfXqh_IBZz
"""

import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')
titanic = pd.read_csv('tested.csv')
flights = sns.load_dataset('flights')
iris = sns.load_dataset('iris')

tips

titanic

"""#SCATTERPLOT WITH (NUMERICAL-NUMERICAL DATA)"""

sns.scatterplot(x='total_bill', y='tip', data=tips,hue='sex',style='smoker',size='size')

"""#HERE WE USED THE BARPLOT WITH BIVARIENT(NUMERICAL-CATEGORICAL DATA)

"""

sns.barplot(x='Pclass',y='Age',data=titanic,hue='Sex')

titanic.head(3)

"""# BOX PLOT (NUMERICAL - CATEGORICAL)"""

sns.boxplot(x='Sex',y='Age',hue='Survived',data=titanic)

"""#DISPLOT (NUMERICAL - CATEGORICAL)"""

sns.displot(x='Age',hue='Survived',data=titanic,kind='kde')

"""#HEATMAP (CATEGORICAL-CATEGORICAL)"""

sns.heatmap(pd.crosstab(titanic['Pclass'],titanic['Survived']))

titanic.groupby('Pclass')['Survived'].mean() * 100

titanic.groupby('Embarked')['Survived'].mean() * 100

"""#CLUSTERMAP (CATEGORICAL - CATEGORICAL)"""

sns.clustermap(pd.crosstab(titanic['Parch'],titanic['Survived']))

"""#PAIRPLOT (COLLECTION OF SCATERPLOT)"""

sns.pairplot(iris,hue='species')

"""#LINEPLOT (NUMERICAL - NUMERICAL)"""

sns.lineplot(x='year',y='passengers',data=flights)

sns.heatmap(flights.pivot_table(values='passengers',index='month',columns='year'))

sns.clustermap(flights.pivot_table(values='passengers',index='month',columns='year'))

