# -*- coding: utf-8 -*-
"""OHE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9Dx9Rr5PY4maiO-0wpzCGkLY89m2C93
"""

import pandas as pd
import numpy as np

df = pd.read_csv('pre-owned cars.csv',usecols=['brand','model','fuel_type','transmission','km_driven','ownership','overall_cost','has_insurance'])

df.sample(10)

df['ownership'].value_counts()

"""# OHE USING PANDAS"""

pd.get_dummies(df,columns=['fuel_type','transmission','ownership'])

pd.get_dummies(df,columns=['fuel_type','transmission','ownership'],drop_first=True)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2)

X_train.head()

X_test.head()

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

X_train_new = ohe.fit_transform(X_train[['fuel_type','ownership']]).toarray()

X_test_new = ohe.fit_transform(X_test[['fuel_type','ownership']]).toarray()

"""we join two X_train used in the horizontal stack

"""

np.hstack((X_train[['brand','km_driven']].values,X_train_new))

"""#OHE WITH TOP CATEGORIES"""

counts = df['brand'].value_counts()

df['brand'].nunique()
threshold = 100

replace = counts[counts <= threshold].index

pd.get_dummies(df['brand'].replace(replace,'uncommon'),dtype=int)

