# -*- coding: utf-8 -*-
"""Ordinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDbiL1A03MvtZMNHbM4JQGS7uxy4W7Ki
"""

import pandas as pd
import numpy as np

df = pd.read_csv('marketing_campaign.csv',usecols=['ID', 'Education', 'Response','Income','Marital_Status'],sep=';')

df.head(20)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2, random_state=42)

X_train

from sklearn.preprocessing import OrdinalEncoder

df.sample(10)

oe = OrdinalEncoder(categories=[['Basic','Graduation','Master','PhD','2n Cycle']])

oe.fit(X_train[['Education']])

X_train = oe.transform(X_train[['Education']])

X_train

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

le.classes_

y_train = le.transform(y_train)

y_train

