# -*- coding: utf-8 -*-
"""outlier_treatment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LS-S_PglF6SpenmNZ7nMyy1FwE9JI1Mr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('placement.csv')

df.sample(5)

plt.figure(figsize=(16,5))

plt.subplot(1,2,1)
sns.histplot(df['cgpa'], kde=True)
plt.title('CGPA Distribution')

plt.subplot(1,2,2)
sns.histplot(df['placement_exam_marks'], kde=True)
plt.title('Placement Exam Marks Distribution')

plt.tight_layout()
plt.show()

print("Mean of cgpa",df['cgpa'].mean())
print("Std value of cgpa",df['cgpa'].std())
print("Min value of cgpa",df['cgpa'].min())
print("Max value of cgpa",df['cgpa'].max())

#Find Boundary Values

print("Highest allowed",df['cgpa'].mean()+ 3*df['cgpa'].std())
print("Lowest allowed",df['cgpa'].mean()- 3*df['cgpa'].std())

df[(df['cgpa'] > 8.80) | (df['cgpa']< 5.11)]

"""#TRIMMING"""

new_df = df[(df['cgpa']< 8.80) & (df['cgpa']> 5.11)]
new_df

"""#CALCULATING THE Z SCORE"""

df['cgpa_zscore'] = (df['cgpa'] - df['cgpa'].mean())/df['cgpa'].std()
df

df[(df['cgpa_zscore'] > 3) | (df['cgpa_zscore']< -3)]

"""#Capping"""

upper_limit = df['cgpa'].mean() + 3*df['cgpa'].std()
lower_limit = df['cgpa'].mean() - 3*df['cgpa'].std()

print("upper limit is",upper_limit)
print("lower limit is",lower_limit)

df['cgpa'] = np.where(
    df['cgpa'] > upper_limit,
    upper_limit,
    np.where(
        df['cgpa'] < lower_limit,
        lower_limit,
        df['cgpa']
    )
)

df['cgpa'].describe()

df.shape

