# -*- coding: utf-8 -*-
"""Predict-using-pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEiGl7lVjze6zt9wKQ3Ert50sKe1Gtw1
"""

import pickle
import numpy as np

pipe = pickle.load(open('pipe.pkl','rb'))

test_input2 = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

pipe.predict(test_input2)

