# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKxtbsy6Ng7lmRi5AZW8NhGtE4F-Afh9
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv('heart.csv')

df.head()

df.shape

X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

rf = RandomForestClassifier()

rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

rf = RandomForestClassifier(max_samples=0.75,random_state=42)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

"""#GRID-SEARCH CV"""

n_estimator = [20,60,100,120]
max_features = [0.2,0.6,1]
max_depth = [2,8,None]
max_samples = [0.5,0.75,1]

param_grid = {'n_estimators':n_estimator,
              'max_features':max_features,
              'max_depth':max_depth,
              'max_samples':max_samples}
print(param_grid)

rf = RandomForestClassifier()

from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(estimator=rf,
                       param_grid=param_grid,
                       cv = 5,
                       verbose=2,
                       n_jobs=-1)

rf_grid.fit(X_train,y_train)

rf_grid.best_params_

rf_grid.best_score_

"""## RandomSearchCV"""

n_estimator = [20,60,100,120]
max_features = [0.2,0.6,1]
max_depth = [2,8,None]
bootstrap = [True,False]

min_samples_split = [2,5]
min_samples_leaf = [1,2]

param_grid = {'n_estimators':n_estimator,
              'max_features':max_features,
              'max_depth':max_depth,
              'bootstrap':bootstrap,
              'min_samples_split':min_samples_split,
              'min_samples_leaf':min_samples_leaf
}
print(param_grid)

from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestClassifier()

rf_grid = RandomizedSearchCV(estimator=rf,
                             param_distributions=param_grid,
                             cv = 5,
                             verbose=2,
                             n_jobs=-1)

rf_grid.fit(X_train,y_train)

rf_grid.best_score_

