# -*- coding: utf-8 -*-
"""RegressionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCLjUv68BnVi5X3VzoAppFXiN_NU51ip
"""

import numpy as np
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import accuracy_score,r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.model_selection import train_test_split

from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing(as_frame=True)
print(housing.DESCR)
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['MedHouseVal'] = housing.target
df.head()

X = df.iloc[:,0:8] # Select columns from index 0 to 7 as features
y = df.iloc[:,8]   # Select the column at index 8 (MedHouseVal) as the target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#

rt = DecisionTreeRegressor(criterion='friedman_mse')
rt.fit(X_train, y_train)

y_pred = rt.predict(X_test)

r2_score(y_test, y_pred)

"""HYPERPARAMETER TUNNING

"""

paran_grid = {
    'max_depth': [2,4,8,10,None],
    'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'min_samples_split': [0.25,0.5,1],
    'max_features': [0.25,0.5,1]
}

reg = GridSearchCV(rt, paran_grid)
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)

r2_score(y_test, y_pred)

