# -*- coding: utf-8 -*-
"""Tree_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_jPocjz7ncEgXXkGAq-4xcVU95p7QlV
"""

!pip install dtreeviz

import graphviz.backend as be

from sklearn.datasets import *
from dtreeviz import *
from IPython.display import Image, display_svg,SVG

from sklearn import tree
clas = tree.DecisionTreeClassifier(max_depth=3)
iris = load_iris()

X_train = iris.data
y_train = iris.target

clas.fit(X_train,y_train)

from  sklearn.tree import plot_tree
plot_tree(clas)

"""# **Classification**"""

from dtreeviz import model
from sklearn import tree
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load dataset
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.3, random_state=42
)

# Train model
clas = tree.DecisionTreeClassifier(max_depth=None)
clas.fit(X_train, y_train)

# Visualize using new dtreeviz API
m = model(
    clas,
    X_train,
    y_train,
    feature_names=iris.feature_names,
    target_name="species",
    class_names=list(iris.target_names)
)

# Display visualization
m.view()

"""## Regression"""

import pandas as pd
regr = tree.DecisionTreeRegressor(max_depth=2)
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing(as_frame=True)
print(housing.DESCR)
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['MedHouseVal'] = housing.target
df.head()

X = df.iloc[:,0:8] # Select columns from index 0 to 7 as features
y = df.iloc[:,8]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#

regr.fit(X_train,y_train)

m = model(
    regr, # Use the regressor model
    X_train,
    y_train,
    feature_names=housing.feature_names, # Use feature names from housing dataset
    target_name="price",
)

# Display visualization
m.view()

"""#3D Regression"""

df_cars = pd.read_csv('Cars (2).csv')
df_cars.head()
df_cars

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Step 1: Load the dataset
df = pd.read_csv("Cars (2).csv")

# Step 2: Convert necessary columns to numeric
df['engine_capacity'] = pd.to_numeric(df['engine_capacity'], errors='coerce')
df['horse_power'] = pd.to_numeric(df['horse_power'], errors='coerce')
df['top_speed'] = pd.to_numeric(df['top_speed'], errors='coerce')

# Step 3: Select the required numeric columns and drop missing values
df = df[['engine_capacity', 'horse_power', 'top_speed']].dropna()

# Step 4: Define input (X) and target (Y) variables
X = df[['engine_capacity', 'horse_power']]
Y = df['top_speed']

# Step 5: Fit Linear Regression
model = LinearRegression()
model.fit(X, Y)

# Step 6: Create a grid for the regression surface
x_surf = np.linspace(df['engine_capacity'].min(), df['engine_capacity'].max(), 30)
y_surf = np.linspace(df['horse_power'].min(), df['horse_power'].max(), 30)

x_surf, y_surf = np.meshgrid(x_surf, y_surf)

# Step 7: Predict values on the grid
z_surf = model.predict(
    np.column_stack((x_surf.ravel(), y_surf.ravel()))
).reshape(x_surf.shape)

# Step 8: Plotting the 3D Graph
fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')

# Scatter actual datapoints
ax.scatter(df['engine_capacity'], df['horse_power'], df['top_speed'], c='blue', s=40)

# Regression surface
ax.plot_surface(x_surf, y_surf, z_surf, alpha=0.5)

# Labels
ax.set_xlabel("Engine Capacity")
ax.set_ylabel("Horse Power")
ax.set_zlabel("Top Speed")
ax.set_title("3D Linear Regression on Car Dataset")

plt.show()

